// Code generated by protoc-gen-go. DO NOT EDIT.
// source: n13t/idm/v0/idm.proto

package n13t_idm_v0

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type IsValidRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IsValidRequest) Reset()         { *m = IsValidRequest{} }
func (m *IsValidRequest) String() string { return proto.CompactTextString(m) }
func (*IsValidRequest) ProtoMessage()    {}
func (*IsValidRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4e677661a4128a4, []int{0}
}

func (m *IsValidRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsValidRequest.Unmarshal(m, b)
}
func (m *IsValidRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsValidRequest.Marshal(b, m, deterministic)
}
func (m *IsValidRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsValidRequest.Merge(m, src)
}
func (m *IsValidRequest) XXX_Size() int {
	return xxx_messageInfo_IsValidRequest.Size(m)
}
func (m *IsValidRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IsValidRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IsValidRequest proto.InternalMessageInfo

func (m *IsValidRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *IsValidRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type IsValidResponse struct {
	V                    bool     `protobuf:"varint,1,opt,name=v,proto3" json:"v,omitempty"`
	Err                  string   `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IsValidResponse) Reset()         { *m = IsValidResponse{} }
func (m *IsValidResponse) String() string { return proto.CompactTextString(m) }
func (*IsValidResponse) ProtoMessage()    {}
func (*IsValidResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4e677661a4128a4, []int{1}
}

func (m *IsValidResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsValidResponse.Unmarshal(m, b)
}
func (m *IsValidResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsValidResponse.Marshal(b, m, deterministic)
}
func (m *IsValidResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsValidResponse.Merge(m, src)
}
func (m *IsValidResponse) XXX_Size() int {
	return xxx_messageInfo_IsValidResponse.Size(m)
}
func (m *IsValidResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IsValidResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IsValidResponse proto.InternalMessageInfo

func (m *IsValidResponse) GetV() bool {
	if m != nil {
		return m.V
	}
	return false
}

func (m *IsValidResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

// Create
type CreateUserRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"` // Deprecated: Do not use.
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4e677661a4128a4, []int{2}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

// Deprecated: Do not use.
func (m *CreateUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type CreateUserResponse struct {
	Err                  string   `protobuf:"bytes,10,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserResponse) Reset()         { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()    {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4e677661a4128a4, []int{3}
}

func (m *CreateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserResponse.Unmarshal(m, b)
}
func (m *CreateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserResponse.Marshal(b, m, deterministic)
}
func (m *CreateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserResponse.Merge(m, src)
}
func (m *CreateUserResponse) XXX_Size() int {
	return xxx_messageInfo_CreateUserResponse.Size(m)
}
func (m *CreateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserResponse proto.InternalMessageInfo

func (m *CreateUserResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

// Update
type UpdateUserRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserRequest) Reset()         { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()    {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4e677661a4128a4, []int{4}
}

func (m *UpdateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserRequest.Unmarshal(m, b)
}
func (m *UpdateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserRequest.Merge(m, src)
}
func (m *UpdateUserRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserRequest.Size(m)
}
func (m *UpdateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserRequest proto.InternalMessageInfo

func (m *UpdateUserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UpdateUserResponse struct {
	Err                  string   `protobuf:"bytes,10,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserResponse) Reset()         { *m = UpdateUserResponse{} }
func (m *UpdateUserResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateUserResponse) ProtoMessage()    {}
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4e677661a4128a4, []int{5}
}

func (m *UpdateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserResponse.Unmarshal(m, b)
}
func (m *UpdateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserResponse.Marshal(b, m, deterministic)
}
func (m *UpdateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserResponse.Merge(m, src)
}
func (m *UpdateUserResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateUserResponse.Size(m)
}
func (m *UpdateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserResponse proto.InternalMessageInfo

func (m *UpdateUserResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func init() {
	proto.RegisterType((*IsValidRequest)(nil), "n13t.idm.v0.IsValidRequest")
	proto.RegisterType((*IsValidResponse)(nil), "n13t.idm.v0.IsValidResponse")
	proto.RegisterType((*CreateUserRequest)(nil), "n13t.idm.v0.CreateUserRequest")
	proto.RegisterType((*CreateUserResponse)(nil), "n13t.idm.v0.CreateUserResponse")
	proto.RegisterType((*UpdateUserRequest)(nil), "n13t.idm.v0.UpdateUserRequest")
	proto.RegisterType((*UpdateUserResponse)(nil), "n13t.idm.v0.UpdateUserResponse")
}

func init() {
	proto.RegisterFile("n13t/idm/v0/idm.proto", fileDescriptor_c4e677661a4128a4)
}

var fileDescriptor_c4e677661a4128a4 = []byte{
	// 388 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0x4f, 0x4f, 0xea, 0x40,
	0x14, 0xc5, 0xd3, 0x3e, 0xc2, 0x83, 0xcb, 0x0b, 0xef, 0x31, 0xc9, 0x33, 0xb5, 0x2a, 0x1a, 0x12,
	0x8d, 0xab, 0xf2, 0x6f, 0x67, 0xdc, 0xa8, 0xb8, 0xc0, 0xc8, 0x06, 0x83, 0x0b, 0x77, 0x95, 0x99,
	0xe8, 0x24, 0x30, 0xad, 0x33, 0x43, 0x0d, 0x9f, 0xc3, 0x2f, 0x6c, 0x66, 0x18, 0xda, 0x69, 0x29,
	0x1b, 0x57, 0x30, 0xe7, 0xdc, 0xfb, 0xbb, 0x67, 0x26, 0xb7, 0xf0, 0x9f, 0xf5, 0x87, 0xb2, 0x4b,
	0xf1, 0xb2, 0x9b, 0xf4, 0xd4, 0x4f, 0x10, 0xf3, 0x48, 0x46, 0xa8, 0xa1, 0xe4, 0x40, 0x9d, 0x93,
	0x9e, 0x7f, 0x60, 0xd7, 0xac, 0x04, 0xe1, 0x9b, 0x22, 0xdf, 0xb3, 0x75, 0x41, 0x42, 0x3e, 0x7f,
	0x37, 0x4e, 0xae, 0x63, 0x41, 0x85, 0x34, 0xfa, 0xa1, 0xad, 0x4b, 0x1e, 0x32, 0x41, 0x8d, 0xd5,
	0xb9, 0x86, 0xe6, 0x58, 0x3c, 0x87, 0x0b, 0x8a, 0xa7, 0xe4, 0x63, 0x45, 0x84, 0x44, 0x4d, 0x70,
	0x29, 0xf6, 0x9c, 0x33, 0xe7, 0xb2, 0x3e, 0x75, 0x29, 0x46, 0x3e, 0xd4, 0xe2, 0x50, 0x88, 0xcf,
	0x88, 0x63, 0xcf, 0xd5, 0x6a, 0x7a, 0xee, 0xf4, 0xe1, 0x6f, 0xda, 0x2d, 0xe2, 0x88, 0x09, 0x82,
	0xfe, 0x80, 0x93, 0xe8, 0xee, 0xda, 0xd4, 0x49, 0xd0, 0x3f, 0xf8, 0x45, 0x38, 0x37, 0x7d, 0xea,
	0x6f, 0xe7, 0x05, 0x5a, 0x77, 0x9c, 0x84, 0x92, 0xcc, 0x04, 0xe1, 0xdb, 0x99, 0xe7, 0x50, 0x51,
	0x17, 0xd4, 0x7d, 0x8d, 0x41, 0x2b, 0xb0, 0x9e, 0x21, 0xd0, 0x75, 0xda, 0x46, 0xed, 0x62, 0x94,
	0x5b, 0xd7, 0x73, 0xac, 0x38, 0x17, 0x80, 0x6c, 0xb6, 0x49, 0x64, 0x32, 0x40, 0x96, 0xe1, 0x0a,
	0x5a, 0xb3, 0x18, 0xff, 0x28, 0x83, 0x9a, 0x61, 0xf7, 0xee, 0x9b, 0x31, 0xf8, 0xaa, 0x00, 0x1a,
	0x63, 0xc2, 0x24, 0x95, 0xeb, 0x49, 0xc8, 0xc2, 0x37, 0xb2, 0x24, 0x4c, 0xa2, 0x09, 0x40, 0x16,
	0x11, 0xb5, 0x73, 0x53, 0x76, 0xde, 0xc5, 0x3f, 0xdd, 0xeb, 0x9b, 0xb9, 0x13, 0x80, 0x2c, 0x4d,
	0x01, 0xb7, 0x73, 0xc5, 0x02, 0xae, 0xe4, 0x1a, 0x37, 0x50, 0x7d, 0xd2, 0x0b, 0x85, 0xfc, 0x5c,
	0xe9, 0x46, 0xdc, 0x62, 0x8e, 0x4a, 0x3d, 0x83, 0x78, 0x80, 0xfa, 0x23, 0x15, 0x52, 0x61, 0x05,
	0x3a, 0xc9, 0x55, 0xa6, 0xfa, 0x16, 0xd4, 0xde, 0x67, 0x1b, 0xd6, 0x08, 0x7e, 0x9b, 0xf5, 0x42,
	0xf9, 0x99, 0xf9, 0x95, 0xf5, 0x8f, 0xcb, 0xcd, 0x8c, 0x72, 0xcf, 0xe6, 0x7c, 0x1d, 0xcb, 0x02,
	0xc5, 0xa8, 0xe5, 0x94, 0xd4, 0xcc, 0x28, 0x23, 0x52, 0x46, 0x31, 0x6a, 0x39, 0x25, 0x35, 0x37,
	0x94, 0xd7, 0xaa, 0xfe, 0xea, 0x86, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x9b, 0x83, 0x1b, 0x21,
	0x00, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// IdentityManagementClient is the client API for IdentityManagement service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type IdentityManagementClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error)
	//    rpc DeleteUser(User) returns (google.protobuf.Empty) {
	//        option (google.api.http) = {
	//			delete: "/v0/users/{sub}"
	//		};
	//    }
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error)
	// for keycloak to check password
	IsValid(ctx context.Context, in *IsValidRequest, opts ...grpc.CallOption) (*IsValidResponse, error)
	// transit engine
	Encrypt(ctx context.Context, in *EncryptRequest, opts ...grpc.CallOption) (*EncryptResponse, error)
	Decrypt(ctx context.Context, in *DecryptRequest, opts ...grpc.CallOption) (*DecryptResponse, error)
}

type identityManagementClient struct {
	cc grpc.ClientConnInterface
}

func NewIdentityManagementClient(cc grpc.ClientConnInterface) IdentityManagementClient {
	return &identityManagementClient{cc}
}

func (c *identityManagementClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, "/n13t.idm.v0.IdentityManagement/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityManagementClient) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error) {
	out := new(UpdateUserResponse)
	err := c.cc.Invoke(ctx, "/n13t.idm.v0.IdentityManagement/UpdateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityManagementClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, "/n13t.idm.v0.IdentityManagement/Search", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityManagementClient) ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error) {
	out := new(ListUsersResponse)
	err := c.cc.Invoke(ctx, "/n13t.idm.v0.IdentityManagement/ListUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityManagementClient) IsValid(ctx context.Context, in *IsValidRequest, opts ...grpc.CallOption) (*IsValidResponse, error) {
	out := new(IsValidResponse)
	err := c.cc.Invoke(ctx, "/n13t.idm.v0.IdentityManagement/IsValid", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityManagementClient) Encrypt(ctx context.Context, in *EncryptRequest, opts ...grpc.CallOption) (*EncryptResponse, error) {
	out := new(EncryptResponse)
	err := c.cc.Invoke(ctx, "/n13t.idm.v0.IdentityManagement/Encrypt", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityManagementClient) Decrypt(ctx context.Context, in *DecryptRequest, opts ...grpc.CallOption) (*DecryptResponse, error) {
	out := new(DecryptResponse)
	err := c.cc.Invoke(ctx, "/n13t.idm.v0.IdentityManagement/Decrypt", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdentityManagementServer is the server API for IdentityManagement service.
type IdentityManagementServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	UpdateUser(context.Context, *UpdateUserRequest) (*UpdateUserResponse, error)
	//    rpc DeleteUser(User) returns (google.protobuf.Empty) {
	//        option (google.api.http) = {
	//			delete: "/v0/users/{sub}"
	//		};
	//    }
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	ListUsers(context.Context, *ListUsersRequest) (*ListUsersResponse, error)
	// for keycloak to check password
	IsValid(context.Context, *IsValidRequest) (*IsValidResponse, error)
	// transit engine
	Encrypt(context.Context, *EncryptRequest) (*EncryptResponse, error)
	Decrypt(context.Context, *DecryptRequest) (*DecryptResponse, error)
}

// UnimplementedIdentityManagementServer can be embedded to have forward compatible implementations.
type UnimplementedIdentityManagementServer struct {
}

func (*UnimplementedIdentityManagementServer) CreateUser(ctx context.Context, req *CreateUserRequest) (*CreateUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (*UnimplementedIdentityManagementServer) UpdateUser(ctx context.Context, req *UpdateUserRequest) (*UpdateUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUser not implemented")
}
func (*UnimplementedIdentityManagementServer) Search(ctx context.Context, req *SearchRequest) (*SearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (*UnimplementedIdentityManagementServer) ListUsers(ctx context.Context, req *ListUsersRequest) (*ListUsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUsers not implemented")
}
func (*UnimplementedIdentityManagementServer) IsValid(ctx context.Context, req *IsValidRequest) (*IsValidResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsValid not implemented")
}
func (*UnimplementedIdentityManagementServer) Encrypt(ctx context.Context, req *EncryptRequest) (*EncryptResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Encrypt not implemented")
}
func (*UnimplementedIdentityManagementServer) Decrypt(ctx context.Context, req *DecryptRequest) (*DecryptResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Decrypt not implemented")
}

func RegisterIdentityManagementServer(s *grpc.Server, srv IdentityManagementServer) {
	s.RegisterService(&_IdentityManagement_serviceDesc, srv)
}

func _IdentityManagement_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityManagementServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/n13t.idm.v0.IdentityManagement/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityManagementServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityManagement_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityManagementServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/n13t.idm.v0.IdentityManagement/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityManagementServer).UpdateUser(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityManagement_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityManagementServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/n13t.idm.v0.IdentityManagement/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityManagementServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityManagement_ListUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityManagementServer).ListUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/n13t.idm.v0.IdentityManagement/ListUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityManagementServer).ListUsers(ctx, req.(*ListUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityManagement_IsValid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsValidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityManagementServer).IsValid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/n13t.idm.v0.IdentityManagement/IsValid",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityManagementServer).IsValid(ctx, req.(*IsValidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityManagement_Encrypt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EncryptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityManagementServer).Encrypt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/n13t.idm.v0.IdentityManagement/Encrypt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityManagementServer).Encrypt(ctx, req.(*EncryptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityManagement_Decrypt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecryptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityManagementServer).Decrypt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/n13t.idm.v0.IdentityManagement/Decrypt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityManagementServer).Decrypt(ctx, req.(*DecryptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _IdentityManagement_serviceDesc = grpc.ServiceDesc{
	ServiceName: "n13t.idm.v0.IdentityManagement",
	HandlerType: (*IdentityManagementServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _IdentityManagement_CreateUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _IdentityManagement_UpdateUser_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _IdentityManagement_Search_Handler,
		},
		{
			MethodName: "ListUsers",
			Handler:    _IdentityManagement_ListUsers_Handler,
		},
		{
			MethodName: "IsValid",
			Handler:    _IdentityManagement_IsValid_Handler,
		},
		{
			MethodName: "Encrypt",
			Handler:    _IdentityManagement_Encrypt_Handler,
		},
		{
			MethodName: "Decrypt",
			Handler:    _IdentityManagement_Decrypt_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "n13t/idm/v0/idm.proto",
}
