// Code generated by protoc-gen-go. DO NOT EDIT.
// source: n13t/idm/v0/idm.proto

package n13t_idm_v0

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type IsValidRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IsValidRequest) Reset()         { *m = IsValidRequest{} }
func (m *IsValidRequest) String() string { return proto.CompactTextString(m) }
func (*IsValidRequest) ProtoMessage()    {}
func (*IsValidRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4e677661a4128a4, []int{0}
}

func (m *IsValidRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsValidRequest.Unmarshal(m, b)
}
func (m *IsValidRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsValidRequest.Marshal(b, m, deterministic)
}
func (m *IsValidRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsValidRequest.Merge(m, src)
}
func (m *IsValidRequest) XXX_Size() int {
	return xxx_messageInfo_IsValidRequest.Size(m)
}
func (m *IsValidRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IsValidRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IsValidRequest proto.InternalMessageInfo

func (m *IsValidRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *IsValidRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type IsValidResponse struct {
	V                    bool     `protobuf:"varint,1,opt,name=v,proto3" json:"v,omitempty"`
	Err                  string   `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IsValidResponse) Reset()         { *m = IsValidResponse{} }
func (m *IsValidResponse) String() string { return proto.CompactTextString(m) }
func (*IsValidResponse) ProtoMessage()    {}
func (*IsValidResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4e677661a4128a4, []int{1}
}

func (m *IsValidResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsValidResponse.Unmarshal(m, b)
}
func (m *IsValidResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsValidResponse.Marshal(b, m, deterministic)
}
func (m *IsValidResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsValidResponse.Merge(m, src)
}
func (m *IsValidResponse) XXX_Size() int {
	return xxx_messageInfo_IsValidResponse.Size(m)
}
func (m *IsValidResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IsValidResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IsValidResponse proto.InternalMessageInfo

func (m *IsValidResponse) GetV() bool {
	if m != nil {
		return m.V
	}
	return false
}

func (m *IsValidResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func init() {
	proto.RegisterType((*IsValidRequest)(nil), "n13t.idm.v0.IsValidRequest")
	proto.RegisterType((*IsValidResponse)(nil), "n13t.idm.v0.IsValidResponse")
}

func init() {
	proto.RegisterFile("n13t/idm/v0/idm.proto", fileDescriptor_c4e677661a4128a4)
}

var fileDescriptor_c4e677661a4128a4 = []byte{
	// 302 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0x3f, 0x4f, 0xf3, 0x30,
	0x10, 0xc6, 0x95, 0x54, 0xea, 0xdb, 0xf7, 0x40, 0x05, 0x59, 0x02, 0x05, 0x83, 0x00, 0x75, 0x62,
	0x4a, 0x5b, 0xba, 0xb2, 0x20, 0xca, 0xd0, 0x21, 0x4b, 0x50, 0xd9, 0x4d, 0x7d, 0x02, 0x4b, 0xd4,
	0x09, 0xf6, 0x35, 0xa8, 0x9f, 0x90, 0xaf, 0x85, 0x92, 0x98, 0xfc, 0x41, 0x66, 0x4a, 0xfc, 0xfc,
	0x9e, 0xfb, 0xc9, 0x39, 0x05, 0x4e, 0xf4, 0x7c, 0x41, 0x53, 0x25, 0xb7, 0xd3, 0x62, 0x56, 0x3e,
	0xe2, 0xdc, 0x64, 0x94, 0xb1, 0x83, 0x32, 0x8e, 0xcb, 0x73, 0x31, 0xe3, 0xa7, 0xdd, 0xce, 0xce,
	0xa2, 0xa9, 0x4b, 0x3c, 0xea, 0xe6, 0x16, 0x85, 0xd9, 0xbc, 0x39, 0x72, 0xd6, 0x25, 0x64, 0x84,
	0xb6, 0x8a, 0x6a, 0x34, 0xb9, 0x83, 0xf1, 0xca, 0x3e, 0x8b, 0x77, 0x25, 0x53, 0xfc, 0xd8, 0xa1,
	0x25, 0x36, 0x86, 0x50, 0xc9, 0x28, 0xb8, 0x0e, 0x6e, 0xfe, 0xa7, 0xa1, 0x92, 0x8c, 0xc3, 0x28,
	0x17, 0xd6, 0x7e, 0x66, 0x46, 0x46, 0x61, 0x95, 0x36, 0xe7, 0xc9, 0x1c, 0x8e, 0x9a, 0x69, 0x9b,
	0x67, 0xda, 0x22, 0x3b, 0x84, 0xa0, 0xa8, 0xa6, 0x47, 0x69, 0x50, 0xb0, 0x63, 0x18, 0xa0, 0x31,
	0x6e, 0xae, 0x7c, 0xbd, 0xfd, 0x1a, 0x00, 0x5b, 0x49, 0xd4, 0xa4, 0x68, 0x9f, 0x08, 0x2d, 0x5e,
	0x71, 0x8b, 0x9a, 0x58, 0x02, 0xf0, 0x60, 0x50, 0x10, 0xae, 0x2d, 0x1a, 0x76, 0x19, 0x77, 0x3e,
	0x38, 0x6e, 0x81, 0xbb, 0x23, 0xbf, 0xfa, 0x93, 0xbb, 0x5b, 0x24, 0x00, 0xeb, 0x5c, 0xfa, 0x75,
	0x2d, 0xf0, 0xeb, 0xba, 0xdc, 0xe9, 0xee, 0x61, 0xf8, 0x54, 0x2d, 0x94, 0xf1, 0x5e, 0xb5, 0x0e,
	0x7f, 0x34, 0xe7, 0x5e, 0xe6, 0x14, 0x4b, 0xf8, 0xe7, 0x56, 0xc5, 0xfa, 0xbd, 0xfe, 0xfa, 0xf9,
	0x85, 0x1f, 0xb6, 0x96, 0x47, 0xbd, 0x31, 0xfb, 0x9c, 0x7e, 0x59, 0x5c, 0xea, 0xb7, 0x34, 0xb0,
	0xb5, 0x2c, 0xd1, 0x67, 0x71, 0xa9, 0xdf, 0xd2, 0xc0, 0xda, 0xf2, 0x32, 0xac, 0xfe, 0xa0, 0xc5,
	0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0d, 0xa6, 0x9a, 0x4e, 0xb4, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// IdentityManagementClient is the client API for IdentityManagement service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type IdentityManagementClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error)
	//    rpc DeleteUser(User) returns (google.protobuf.Empty) {
	//        option (google.api.http) = {
	//			delete: "/v0/users/{sub}"
	//		};
	//    }
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	// for keycloak to check password
	IsValid(ctx context.Context, in *IsValidRequest, opts ...grpc.CallOption) (*IsValidResponse, error)
	// transit engine
	Encrypt(ctx context.Context, in *EncryptRequest, opts ...grpc.CallOption) (*EncryptResponse, error)
	Decrypt(ctx context.Context, in *DecryptRequest, opts ...grpc.CallOption) (*DecryptResponse, error)
}

type identityManagementClient struct {
	cc grpc.ClientConnInterface
}

func NewIdentityManagementClient(cc grpc.ClientConnInterface) IdentityManagementClient {
	return &identityManagementClient{cc}
}

func (c *identityManagementClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, "/n13t.idm.v0.IdentityManagement/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityManagementClient) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error) {
	out := new(UpdateUserResponse)
	err := c.cc.Invoke(ctx, "/n13t.idm.v0.IdentityManagement/UpdateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityManagementClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, "/n13t.idm.v0.IdentityManagement/Search", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityManagementClient) IsValid(ctx context.Context, in *IsValidRequest, opts ...grpc.CallOption) (*IsValidResponse, error) {
	out := new(IsValidResponse)
	err := c.cc.Invoke(ctx, "/n13t.idm.v0.IdentityManagement/IsValid", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityManagementClient) Encrypt(ctx context.Context, in *EncryptRequest, opts ...grpc.CallOption) (*EncryptResponse, error) {
	out := new(EncryptResponse)
	err := c.cc.Invoke(ctx, "/n13t.idm.v0.IdentityManagement/Encrypt", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityManagementClient) Decrypt(ctx context.Context, in *DecryptRequest, opts ...grpc.CallOption) (*DecryptResponse, error) {
	out := new(DecryptResponse)
	err := c.cc.Invoke(ctx, "/n13t.idm.v0.IdentityManagement/Decrypt", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdentityManagementServer is the server API for IdentityManagement service.
type IdentityManagementServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	UpdateUser(context.Context, *UpdateUserRequest) (*UpdateUserResponse, error)
	//    rpc DeleteUser(User) returns (google.protobuf.Empty) {
	//        option (google.api.http) = {
	//			delete: "/v0/users/{sub}"
	//		};
	//    }
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	// for keycloak to check password
	IsValid(context.Context, *IsValidRequest) (*IsValidResponse, error)
	// transit engine
	Encrypt(context.Context, *EncryptRequest) (*EncryptResponse, error)
	Decrypt(context.Context, *DecryptRequest) (*DecryptResponse, error)
}

// UnimplementedIdentityManagementServer can be embedded to have forward compatible implementations.
type UnimplementedIdentityManagementServer struct {
}

func (*UnimplementedIdentityManagementServer) CreateUser(ctx context.Context, req *CreateUserRequest) (*CreateUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (*UnimplementedIdentityManagementServer) UpdateUser(ctx context.Context, req *UpdateUserRequest) (*UpdateUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUser not implemented")
}
func (*UnimplementedIdentityManagementServer) Search(ctx context.Context, req *SearchRequest) (*SearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (*UnimplementedIdentityManagementServer) IsValid(ctx context.Context, req *IsValidRequest) (*IsValidResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsValid not implemented")
}
func (*UnimplementedIdentityManagementServer) Encrypt(ctx context.Context, req *EncryptRequest) (*EncryptResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Encrypt not implemented")
}
func (*UnimplementedIdentityManagementServer) Decrypt(ctx context.Context, req *DecryptRequest) (*DecryptResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Decrypt not implemented")
}

func RegisterIdentityManagementServer(s *grpc.Server, srv IdentityManagementServer) {
	s.RegisterService(&_IdentityManagement_serviceDesc, srv)
}

func _IdentityManagement_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityManagementServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/n13t.idm.v0.IdentityManagement/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityManagementServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityManagement_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityManagementServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/n13t.idm.v0.IdentityManagement/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityManagementServer).UpdateUser(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityManagement_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityManagementServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/n13t.idm.v0.IdentityManagement/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityManagementServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityManagement_IsValid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsValidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityManagementServer).IsValid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/n13t.idm.v0.IdentityManagement/IsValid",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityManagementServer).IsValid(ctx, req.(*IsValidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityManagement_Encrypt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EncryptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityManagementServer).Encrypt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/n13t.idm.v0.IdentityManagement/Encrypt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityManagementServer).Encrypt(ctx, req.(*EncryptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityManagement_Decrypt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecryptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityManagementServer).Decrypt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/n13t.idm.v0.IdentityManagement/Decrypt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityManagementServer).Decrypt(ctx, req.(*DecryptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _IdentityManagement_serviceDesc = grpc.ServiceDesc{
	ServiceName: "n13t.idm.v0.IdentityManagement",
	HandlerType: (*IdentityManagementServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _IdentityManagement_CreateUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _IdentityManagement_UpdateUser_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _IdentityManagement_Search_Handler,
		},
		{
			MethodName: "IsValid",
			Handler:    _IdentityManagement_IsValid_Handler,
		},
		{
			MethodName: "Encrypt",
			Handler:    _IdentityManagement_Encrypt_Handler,
		},
		{
			MethodName: "Decrypt",
			Handler:    _IdentityManagement_Decrypt_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "n13t/idm/v0/idm.proto",
}
