// Code generated by protoc-gen-go. DO NOT EDIT.
// source: n13t/idm/v0/list.proto

package n13t_idm_v0

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListUsersRequest struct {
	// Optional. The maximum number of Users to return in the response.
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Optional. A pagination token returned from a previous call to `ListUsers`
	// that indicates where this listing should continue from.
	PageToken            string   `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUsersRequest) Reset()         { *m = ListUsersRequest{} }
func (m *ListUsersRequest) String() string { return proto.CompactTextString(m) }
func (*ListUsersRequest) ProtoMessage()    {}
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_42dabac6d506bfca, []int{0}
}

func (m *ListUsersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUsersRequest.Unmarshal(m, b)
}
func (m *ListUsersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUsersRequest.Marshal(b, m, deterministic)
}
func (m *ListUsersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUsersRequest.Merge(m, src)
}
func (m *ListUsersRequest) XXX_Size() int {
	return xxx_messageInfo_ListUsersRequest.Size(m)
}
func (m *ListUsersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUsersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListUsersRequest proto.InternalMessageInfo

func (m *ListUsersRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListUsersRequest) GetPageToken() string {
	if m != nil {
		return m.PageToken
	}
	return ""
}

type ListUsersResponse struct {
	Users []*User `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	// A pagination token returned from a previous call to `ListUsers`
	// that indicates from where listing should continue.
	NextPageToken        string   `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUsersResponse) Reset()         { *m = ListUsersResponse{} }
func (m *ListUsersResponse) String() string { return proto.CompactTextString(m) }
func (*ListUsersResponse) ProtoMessage()    {}
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_42dabac6d506bfca, []int{1}
}

func (m *ListUsersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUsersResponse.Unmarshal(m, b)
}
func (m *ListUsersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUsersResponse.Marshal(b, m, deterministic)
}
func (m *ListUsersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUsersResponse.Merge(m, src)
}
func (m *ListUsersResponse) XXX_Size() int {
	return xxx_messageInfo_ListUsersResponse.Size(m)
}
func (m *ListUsersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUsersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListUsersResponse proto.InternalMessageInfo

func (m *ListUsersResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *ListUsersResponse) GetNextPageToken() string {
	if m != nil {
		return m.NextPageToken
	}
	return ""
}

func init() {
	proto.RegisterType((*ListUsersRequest)(nil), "n13t.idm.v0.ListUsersRequest")
	proto.RegisterType((*ListUsersResponse)(nil), "n13t.idm.v0.ListUsersResponse")
}

func init() {
	proto.RegisterFile("n13t/idm/v0/list.proto", fileDescriptor_42dabac6d506bfca)
}

var fileDescriptor_42dabac6d506bfca = []byte{
	// 199 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8e, 0x41, 0x6b, 0x83, 0x40,
	0x10, 0x46, 0x51, 0xb1, 0xd4, 0x91, 0xd2, 0xba, 0x87, 0x22, 0x2d, 0x05, 0xf1, 0xd0, 0x7a, 0x5a,
	0x6d, 0xfd, 0x1b, 0xa5, 0x94, 0x6d, 0x73, 0x96, 0x04, 0x87, 0xb0, 0x24, 0xee, 0x1a, 0x67, 0x95,
	0xe0, 0xaf, 0x0f, 0xbb, 0x12, 0x30, 0xd7, 0x37, 0x8f, 0x79, 0x1f, 0x3c, 0xab, 0xcf, 0xda, 0x94,
	0xb2, 0xed, 0xca, 0xa9, 0x2a, 0x8f, 0x92, 0x0c, 0xef, 0x07, 0x6d, 0x34, 0x8b, 0x2d, 0xe7, 0xb2,
	0xed, 0xf8, 0x54, 0xbd, 0xdc, 0x48, 0x23, 0xe1, 0xb0, 0x48, 0xf9, 0x0f, 0x3c, 0x7d, 0x4b, 0x32,
	0x1b, 0xc2, 0x81, 0x04, 0x9e, 0x46, 0x24, 0xc3, 0x5e, 0x21, 0xea, 0xb7, 0x7b, 0x6c, 0x48, 0xce,
	0x98, 0xfa, 0x99, 0x57, 0x84, 0xe2, 0xde, 0x82, 0x3f, 0x39, 0x23, 0x7b, 0x03, 0x70, 0x47, 0xa3,
	0x0f, 0xa8, 0xd2, 0x20, 0xf3, 0x8a, 0x48, 0x38, 0xfd, 0xdf, 0x82, 0xbc, 0x85, 0x64, 0xf5, 0x8f,
	0x7a, 0xad, 0x08, 0xd9, 0x07, 0x84, 0x36, 0x49, 0xa9, 0x97, 0x05, 0x45, 0xfc, 0x95, 0xf0, 0xd5,
	0x32, 0x6e, 0x55, 0xb1, 0xdc, 0xd9, 0x3b, 0x3c, 0x2a, 0x3c, 0x9b, 0x66, 0x55, 0xf0, 0x5d, 0xe1,
	0xc1, 0xe2, 0xdf, 0x6b, 0x65, 0x77, 0xe7, 0xc6, 0xd7, 0x97, 0x00, 0x00, 0x00, 0xff, 0xff, 0x22,
	0x7a, 0x87, 0x71, 0xfb, 0x00, 0x00, 0x00,
}
