// Code generated by protoc-gen-go. DO NOT EDIT.
// source: n13t/idm/v0/search.proto

package n13t_idm_v0

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SearchRequest struct {
	Index                string   `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	Query                string   `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	Limit                int32    `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int32    `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchRequest) Reset()         { *m = SearchRequest{} }
func (m *SearchRequest) String() string { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()    {}
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_81f6c60b662e27bb, []int{0}
}

func (m *SearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchRequest.Unmarshal(m, b)
}
func (m *SearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchRequest.Marshal(b, m, deterministic)
}
func (m *SearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchRequest.Merge(m, src)
}
func (m *SearchRequest) XXX_Size() int {
	return xxx_messageInfo_SearchRequest.Size(m)
}
func (m *SearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchRequest proto.InternalMessageInfo

func (m *SearchRequest) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *SearchRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *SearchRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *SearchRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type SearchResponse struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchResponse) Reset()         { *m = SearchResponse{} }
func (m *SearchResponse) String() string { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()    {}
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_81f6c60b662e27bb, []int{1}
}

func (m *SearchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchResponse.Unmarshal(m, b)
}
func (m *SearchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchResponse.Marshal(b, m, deterministic)
}
func (m *SearchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchResponse.Merge(m, src)
}
func (m *SearchResponse) XXX_Size() int {
	return xxx_messageInfo_SearchResponse.Size(m)
}
func (m *SearchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchResponse proto.InternalMessageInfo

func (m *SearchResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func init() {
	proto.RegisterType((*SearchRequest)(nil), "n13t.idm.v0.SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "n13t.idm.v0.SearchResponse")
}

func init() {
	proto.RegisterFile("n13t/idm/v0/search.proto", fileDescriptor_81f6c60b662e27bb)
}

var fileDescriptor_81f6c60b662e27bb = []byte{
	// 189 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8e, 0xc1, 0x8a, 0x83, 0x30,
	0x14, 0x45, 0xc9, 0x38, 0x0a, 0x13, 0x99, 0x81, 0x09, 0x83, 0x84, 0x59, 0x89, 0x9b, 0xba, 0x8a,
	0xb6, 0xae, 0xfa, 0x1b, 0x29, 0xfd, 0x80, 0xb6, 0x3e, 0x69, 0xa0, 0x1a, 0xcd, 0x8b, 0xd2, 0xfe,
	0x7d, 0x49, 0xd2, 0x82, 0xcb, 0x73, 0xee, 0x7d, 0xbc, 0x4b, 0xf9, 0xb0, 0x6d, 0x6c, 0xa5, 0xda,
	0xbe, 0x5a, 0xea, 0x0a, 0xe1, 0x64, 0x2e, 0x57, 0x31, 0x1a, 0x6d, 0x35, 0x4b, 0x5d, 0x22, 0x54,
	0xdb, 0x8b, 0xa5, 0xfe, 0xcf, 0xd6, 0xb5, 0x19, 0xc1, 0x84, 0x52, 0xa1, 0xe8, 0xf7, 0xc1, 0x1f,
	0x49, 0x98, 0x66, 0x40, 0xcb, 0xfe, 0x68, 0xac, 0x86, 0x16, 0xee, 0x9c, 0xe4, 0xa4, 0xfc, 0x92,
	0x01, 0x9c, 0x9d, 0x66, 0x30, 0x0f, 0xfe, 0x11, 0xac, 0x07, 0x67, 0x6f, 0xaa, 0x57, 0x96, 0x47,
	0x39, 0x29, 0x63, 0x19, 0x80, 0x65, 0x34, 0xd1, 0x5d, 0x87, 0x60, 0xf9, 0xa7, 0xd7, 0x2f, 0x2a,
	0xf6, 0xf4, 0xe7, 0xfd, 0x0a, 0x47, 0x3d, 0x20, 0xb0, 0x0d, 0x8d, 0xdd, 0x14, 0xe4, 0x24, 0x8f,
	0xca, 0x74, 0xf7, 0x2b, 0x56, 0x8b, 0xc5, 0x11, 0xc1, 0xc8, 0x90, 0x9f, 0x13, 0x3f, 0xb6, 0x79,
	0x06, 0x00, 0x00, 0xff, 0xff, 0xca, 0x98, 0x5d, 0x38, 0xed, 0x00, 0x00, 0x00,
}
