// Code generated by protoc-gen-go. DO NOT EDIT.
// source: n13t/idm/v0/transit.proto

package n13t_idm_v0

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TransitData struct {
	Plaintext            string   `protobuf:"bytes,1,opt,name=plaintext,proto3" json:"plaintext,omitempty"`
	Ciphertext           string   `protobuf:"bytes,2,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransitData) Reset()         { *m = TransitData{} }
func (m *TransitData) String() string { return proto.CompactTextString(m) }
func (*TransitData) ProtoMessage()    {}
func (*TransitData) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a7665d79a06aae2, []int{0}
}

func (m *TransitData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransitData.Unmarshal(m, b)
}
func (m *TransitData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransitData.Marshal(b, m, deterministic)
}
func (m *TransitData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransitData.Merge(m, src)
}
func (m *TransitData) XXX_Size() int {
	return xxx_messageInfo_TransitData.Size(m)
}
func (m *TransitData) XXX_DiscardUnknown() {
	xxx_messageInfo_TransitData.DiscardUnknown(m)
}

var xxx_messageInfo_TransitData proto.InternalMessageInfo

func (m *TransitData) GetPlaintext() string {
	if m != nil {
		return m.Plaintext
	}
	return ""
}

func (m *TransitData) GetCiphertext() string {
	if m != nil {
		return m.Ciphertext
	}
	return ""
}

func init() {
	proto.RegisterType((*TransitData)(nil), "n13t.idm.v0.TransitData")
}

func init() {
	proto.RegisterFile("n13t/idm/v0/transit.proto", fileDescriptor_6a7665d79a06aae2)
}

var fileDescriptor_6a7665d79a06aae2 = []byte{
	// 117 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0xcc, 0x33, 0x34, 0x2e,
	0xd1, 0xcf, 0x4c, 0xc9, 0xd5, 0x2f, 0x33, 0xd0, 0x2f, 0x29, 0x4a, 0xcc, 0x2b, 0xce, 0x2c, 0xd1,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x06, 0x49, 0xe9, 0x65, 0xa6, 0xe4, 0xea, 0x95, 0x19,
	0x28, 0x79, 0x73, 0x71, 0x87, 0x40, 0x64, 0x5d, 0x12, 0x4b, 0x12, 0x85, 0x64, 0xb8, 0x38, 0x0b,
	0x72, 0x12, 0x33, 0xf3, 0x4a, 0x52, 0x2b, 0x4a, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x10,
	0x02, 0x42, 0x72, 0x5c, 0x5c, 0xc9, 0x99, 0x05, 0x19, 0xa9, 0x45, 0x60, 0x69, 0x26, 0xb0, 0x34,
	0x92, 0x48, 0x12, 0x1b, 0xd8, 0x02, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe2, 0x20, 0x87,
	0x98, 0x7d, 0x00, 0x00, 0x00,
}
