// Code generated by protoc-gen-go. DO NOT EDIT.
// source: n13t/idm/v0/user.proto

package n13t_idm_v0

import (
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//*
// Represents the user
//
// Compatible with OIDC (OpenID Connect)
type User struct {
	Enabled bool `protobuf:"varint,9,opt,name=enabled,proto3" json:"enabled,omitempty"`
	//    google.protobuf.Timestamp created_at = 101;     // ???
	Attributes map[string]*any.Any `protobuf:"bytes,100,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// OpenId Standard Claims Members (https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims)
	// Subject - Identifier for the End-User at the Issuer.
	Sub string `protobuf:"bytes,10,opt,name=sub,proto3" json:"sub,omitempty"`
	// End-User's full name in displayable form including all name parts, possibly including titles and suffixes, ordered according to the End-User's locale and preferences.
	Name string `protobuf:"bytes,11,opt,name=name,proto3" json:"name,omitempty"`
	// Given name(s) or first name(s) of the End-User.
	GivenName string `protobuf:"bytes,12,opt,name=given_name,json=givenName,proto3" json:"given_name,omitempty"`
	// Surname(s) or last name(s) of the End-User
	FamilyName string `protobuf:"bytes,14,opt,name=family_name,json=familyName,proto3" json:"family_name,omitempty"`
	// Middle name(s) of the End-User
	MiddleName string `protobuf:"bytes,15,opt,name=middle_name,json=middleName,proto3" json:"middle_name,omitempty"`
	// Casual name of the End-User
	Nickname string `protobuf:"bytes,16,opt,name=nickname,proto3" json:"nickname,omitempty"`
	// Shorthand name by which the End-User wishes to be referred to at the RP, such as janedoe or j.doe.
	// This value MAY be any valid JSON string including special characters such as @, /, or whitespace (not unique!, see https://openid.net/specs/openid-connect-basic-1_0.html#ClaimStability)
	PreferredUsername string `protobuf:"bytes,17,opt,name=preferred_username,json=preferredUsername,proto3" json:"preferred_username,omitempty"`
	Profile           string `protobuf:"bytes,20,opt,name=profile,proto3" json:"profile,omitempty"`
	Picture           string `protobuf:"bytes,21,opt,name=picture,proto3" json:"picture,omitempty"`
	Website           string `protobuf:"bytes,22,opt,name=website,proto3" json:"website,omitempty"`
	// RFC5322  (not unique!, see https://openid.net/specs/openid-connect-basic-1_0.html#ClaimStability)
	Email         string `protobuf:"bytes,30,opt,name=email,proto3" json:"email,omitempty"`
	EmailVerified bool   `protobuf:"varint,31,opt,name=email_verified,json=emailVerified,proto3" json:"email_verified,omitempty"`
	Gender        string `protobuf:"bytes,32,opt,name=gender,proto3" json:"gender,omitempty"`
	// ISO 8601:2004 YYYY-MM-DD format. The year MAY be 0000, indicating that it is omitted. To represent only the year, YYYY format is allowed.
	Birthdate string `protobuf:"bytes,33,opt,name=birthdate,proto3" json:"birthdate,omitempty"`
	// String from zoneinfo time zone database (the tz database) representing the End-User's time zone. For example, Europe/Paris or America/Los_Angeles.
	Zoneinfo string `protobuf:"bytes,34,opt,name=zoneinfo,proto3" json:"zoneinfo,omitempty"`
	// End-User's locale, represented as a BCP47 [RFC5646] language tag.
	// This is typically an ISO 639-1 Alpha-2 [ISO639‑1] language code in lowercase and an ISO 3166-1 Alpha-2 [ISO3166‑1] country code in uppercase, separated by a dash. For example, en-US or fr-CA.
	// As a compatibility note, some implementations have used an underscore as the separator rather than a dash, for example, en_US; Relying Parties MAY choose to accept this locale syntax as well.
	Locale string `protobuf:"bytes,35,opt,name=locale,proto3" json:"locale,omitempty"`
	// Ex: +1 (425) 555-1212 or +56 (2) 687 2400   (E.164)
	//  or +1 (604) 555-1234;ext=5678              (RFC3966)
	// see E.164/RFC3966
	PhoneNumber         string        `protobuf:"bytes,40,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	PhoneNumberVerified bool          `protobuf:"varint,41,opt,name=phone_number_verified,json=phoneNumberVerified,proto3" json:"phone_number_verified,omitempty"`
	Address             *User_Address `protobuf:"bytes,42,opt,name=address,proto3" json:"address,omitempty"`
	// custom fields
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,102,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Username             string               `protobuf:"bytes,200,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4b0f5de40cf5538, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *User) GetAttributes() map[string]*any.Any {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *User) GetSub() string {
	if m != nil {
		return m.Sub
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetGivenName() string {
	if m != nil {
		return m.GivenName
	}
	return ""
}

func (m *User) GetFamilyName() string {
	if m != nil {
		return m.FamilyName
	}
	return ""
}

func (m *User) GetMiddleName() string {
	if m != nil {
		return m.MiddleName
	}
	return ""
}

func (m *User) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *User) GetPreferredUsername() string {
	if m != nil {
		return m.PreferredUsername
	}
	return ""
}

func (m *User) GetProfile() string {
	if m != nil {
		return m.Profile
	}
	return ""
}

func (m *User) GetPicture() string {
	if m != nil {
		return m.Picture
	}
	return ""
}

func (m *User) GetWebsite() string {
	if m != nil {
		return m.Website
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetEmailVerified() bool {
	if m != nil {
		return m.EmailVerified
	}
	return false
}

func (m *User) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *User) GetBirthdate() string {
	if m != nil {
		return m.Birthdate
	}
	return ""
}

func (m *User) GetZoneinfo() string {
	if m != nil {
		return m.Zoneinfo
	}
	return ""
}

func (m *User) GetLocale() string {
	if m != nil {
		return m.Locale
	}
	return ""
}

func (m *User) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *User) GetPhoneNumberVerified() bool {
	if m != nil {
		return m.PhoneNumberVerified
	}
	return false
}

func (m *User) GetAddress() *User_Address {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *User) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

// https://openid.net/specs/openid-connect-core-1_0.html#AddressClaim
type User_Address struct {
	Formatted            string   `protobuf:"bytes,1,opt,name=formatted,proto3" json:"formatted,omitempty"`
	StreetAddress        string   `protobuf:"bytes,2,opt,name=street_address,json=streetAddress,proto3" json:"street_address,omitempty"`
	Locality             string   `protobuf:"bytes,3,opt,name=locality,proto3" json:"locality,omitempty"`
	Region               string   `protobuf:"bytes,4,opt,name=region,proto3" json:"region,omitempty"`
	PostalCode           string   `protobuf:"bytes,5,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	Country              string   `protobuf:"bytes,6,opt,name=country,proto3" json:"country,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User_Address) Reset()         { *m = User_Address{} }
func (m *User_Address) String() string { return proto.CompactTextString(m) }
func (*User_Address) ProtoMessage()    {}
func (*User_Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4b0f5de40cf5538, []int{0, 1}
}

func (m *User_Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User_Address.Unmarshal(m, b)
}
func (m *User_Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User_Address.Marshal(b, m, deterministic)
}
func (m *User_Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User_Address.Merge(m, src)
}
func (m *User_Address) XXX_Size() int {
	return xxx_messageInfo_User_Address.Size(m)
}
func (m *User_Address) XXX_DiscardUnknown() {
	xxx_messageInfo_User_Address.DiscardUnknown(m)
}

var xxx_messageInfo_User_Address proto.InternalMessageInfo

func (m *User_Address) GetFormatted() string {
	if m != nil {
		return m.Formatted
	}
	return ""
}

func (m *User_Address) GetStreetAddress() string {
	if m != nil {
		return m.StreetAddress
	}
	return ""
}

func (m *User_Address) GetLocality() string {
	if m != nil {
		return m.Locality
	}
	return ""
}

func (m *User_Address) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *User_Address) GetPostalCode() string {
	if m != nil {
		return m.PostalCode
	}
	return ""
}

func (m *User_Address) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

type CreateUserRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4b0f5de40cf5538, []int{1}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *CreateUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type CreateUserResponse struct {
	Err                  string   `protobuf:"bytes,10,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserResponse) Reset()         { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()    {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4b0f5de40cf5538, []int{2}
}

func (m *CreateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserResponse.Unmarshal(m, b)
}
func (m *CreateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserResponse.Marshal(b, m, deterministic)
}
func (m *CreateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserResponse.Merge(m, src)
}
func (m *CreateUserResponse) XXX_Size() int {
	return xxx_messageInfo_CreateUserResponse.Size(m)
}
func (m *CreateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserResponse proto.InternalMessageInfo

func (m *CreateUserResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type UpdateUserRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserRequest) Reset()         { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()    {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4b0f5de40cf5538, []int{3}
}

func (m *UpdateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserRequest.Unmarshal(m, b)
}
func (m *UpdateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserRequest.Merge(m, src)
}
func (m *UpdateUserRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserRequest.Size(m)
}
func (m *UpdateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserRequest proto.InternalMessageInfo

func (m *UpdateUserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UpdateUserResponse struct {
	Err                  string   `protobuf:"bytes,10,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserResponse) Reset()         { *m = UpdateUserResponse{} }
func (m *UpdateUserResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateUserResponse) ProtoMessage()    {}
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4b0f5de40cf5538, []int{4}
}

func (m *UpdateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserResponse.Unmarshal(m, b)
}
func (m *UpdateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserResponse.Marshal(b, m, deterministic)
}
func (m *UpdateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserResponse.Merge(m, src)
}
func (m *UpdateUserResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateUserResponse.Size(m)
}
func (m *UpdateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserResponse proto.InternalMessageInfo

func (m *UpdateUserResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "n13t.idm.v0.User")
	proto.RegisterMapType((map[string]*any.Any)(nil), "n13t.idm.v0.User.AttributesEntry")
	proto.RegisterType((*User_Address)(nil), "n13t.idm.v0.User.Address")
	proto.RegisterType((*CreateUserRequest)(nil), "n13t.idm.v0.CreateUserRequest")
	proto.RegisterType((*CreateUserResponse)(nil), "n13t.idm.v0.CreateUserResponse")
	proto.RegisterType((*UpdateUserRequest)(nil), "n13t.idm.v0.UpdateUserRequest")
	proto.RegisterType((*UpdateUserResponse)(nil), "n13t.idm.v0.UpdateUserResponse")
}

func init() {
	proto.RegisterFile("n13t/idm/v0/user.proto", fileDescriptor_f4b0f5de40cf5538)
}

var fileDescriptor_f4b0f5de40cf5538 = []byte{
	// 865 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x4b, 0x6f, 0x23, 0x45,
	0x10, 0xd6, 0xc4, 0x79, 0xd8, 0xe5, 0x7d, 0xb9, 0xd9, 0x0d, 0xbd, 0x06, 0x11, 0xc7, 0x78, 0x97,
	0xb1, 0x8d, 0xc7, 0x59, 0x47, 0x48, 0xb0, 0x17, 0xd6, 0x8e, 0xf6, 0x02, 0x28, 0x87, 0x81, 0xec,
	0x81, 0x3c, 0xac, 0xb1, 0xa7, 0xec, 0x6d, 0xed, 0x3c, 0x4c, 0x4f, 0x8f, 0x23, 0x2f, 0x20, 0x71,
	0xe4, 0x87, 0xf0, 0x03, 0x10, 0x77, 0xee, 0xfc, 0x26, 0x9f, 0x50, 0x57, 0xcf, 0x38, 0x26, 0x01,
	0x89, 0xcd, 0x6d, 0xea, 0xfb, 0xbe, 0xfa, 0xba, 0xaa, 0xab, 0xa7, 0x60, 0x37, 0x7a, 0x76, 0xa8,
	0xba, 0xc2, 0x0f, 0xbb, 0xf3, 0x83, 0x6e, 0x9a, 0xa0, 0x74, 0x66, 0x32, 0x56, 0x31, 0x2b, 0x6b,
	0xdc, 0x11, 0x7e, 0xe8, 0xcc, 0x0f, 0xaa, 0x8f, 0xa7, 0x71, 0x3c, 0x0d, 0xb0, 0x4b, 0xd4, 0x28,
	0x9d, 0x74, 0xbd, 0x68, 0x61, 0x74, 0xd5, 0xbd, 0xeb, 0x94, 0x12, 0x21, 0x26, 0xca, 0x0b, 0x67,
	0x99, 0xe0, 0xfd, 0xb9, 0x17, 0x08, 0xdf, 0x53, 0xd8, 0xcd, 0x3f, 0x0c, 0x51, 0xff, 0xad, 0x0c,
	0x9b, 0x27, 0x09, 0x4a, 0xc6, 0x61, 0x07, 0x23, 0x6f, 0x14, 0xa0, 0xcf, 0x4b, 0x35, 0xcb, 0x2e,
	0xba, 0x79, 0xc8, 0xfa, 0x00, 0x9e, 0x52, 0x52, 0x8c, 0x52, 0x85, 0x09, 0xf7, 0x6b, 0x05, 0xbb,
	0xdc, 0xdb, 0x77, 0xd6, 0x2a, 0x73, 0xb4, 0x81, 0xd3, 0x5f, 0x69, 0x5e, 0x46, 0x4a, 0x2e, 0xdc,
	0xb5, 0x24, 0x56, 0x85, 0x42, 0x92, 0x8e, 0x38, 0xd4, 0x2c, 0xbb, 0x34, 0x28, 0x2e, 0x07, 0x5b,
	0xb2, 0xf0, 0xbb, 0x65, 0xb9, 0x1a, 0x64, 0x03, 0xd8, 0x8c, 0xbc, 0x10, 0x79, 0x99, 0x48, 0x67,
	0x39, 0x68, 0xcb, 0xa6, 0xfd, 0xcb, 0x46, 0xaf, 0x71, 0x71, 0x7a, 0x71, 0x7a, 0xd0, 0xf9, 0xe2,
	0xbc, 0xdf, 0xf9, 0xde, 0xeb, 0xbc, 0x3d, 0x6f, 0xdb, 0xb5, 0x6b, 0x40, 0xb3, 0xd5, 0x70, 0x29,
	0x97, 0x7d, 0x03, 0x30, 0x15, 0x73, 0x8c, 0x86, 0xe4, 0x74, 0x87, 0x9c, 0x3a, 0xcb, 0x41, 0x4b,
	0xda, 0xf6, 0x8b, 0xff, 0x69, 0x54, 0x22, 0x83, 0x63, 0xed, 0x76, 0x0c, 0xe5, 0x89, 0x17, 0x8a,
	0x60, 0x61, 0xec, 0xee, 0xdd, 0xc6, 0x0e, 0x8c, 0x43, 0xee, 0x17, 0x0a, 0xdf, 0x0f, 0xd0, 0xf8,
	0xdd, 0xbf, 0x95, 0x9f, 0x71, 0x20, 0xbf, 0xaf, 0xa0, 0x18, 0x89, 0xf1, 0x1b, 0x32, 0x7b, 0x70,
	0xab, 0x5b, 0x5b, 0xe5, 0xb3, 0x0e, 0xb0, 0x99, 0xc4, 0x09, 0x4a, 0x89, 0xfe, 0x50, 0xbf, 0x3c,
	0x72, 0xad, 0x68, 0x57, 0xb7, 0xb2, 0x62, 0x4e, 0x32, 0x82, 0xd5, 0x61, 0x67, 0x26, 0xe3, 0x89,
	0x08, 0x90, 0x3f, 0x5c, 0x1b, 0xe6, 0xaf, 0x96, 0xe5, 0xe6, 0x04, 0x69, 0xc4, 0x58, 0xa5, 0x12,
	0xf9, 0xa3, 0x1b, 0x1a, 0x43, 0x68, 0xcd, 0x25, 0x8e, 0x12, 0xa1, 0x90, 0xef, 0x5e, 0xd7, 0x64,
	0x04, 0xfb, 0x1a, 0xb6, 0x30, 0xf4, 0x44, 0xc0, 0x3f, 0x22, 0xc5, 0x67, 0xcb, 0x41, 0x4f, 0x1e,
	0xf4, 0x9c, 0x8b, 0xb3, 0xcb, 0xb6, 0x7d, 0xda, 0x69, 0x3b, 0x9f, 0x9c, 0x9f, 0x5d, 0xb6, 0x9b,
	0xad, 0x17, 0x26, 0x76, 0x4c, 0x74, 0xe6, 0xfc, 0x23, 0x6c, 0xb8, 0xc6, 0x83, 0x3d, 0x81, 0x7b,
	0xf4, 0x31, 0x9c, 0xa3, 0x14, 0x13, 0x81, 0x3e, 0xdf, 0xa3, 0x57, 0x7e, 0x97, 0xd0, 0x57, 0x19,
	0xc8, 0x76, 0x61, 0x7b, 0x8a, 0x91, 0x8f, 0x92, 0xd7, 0xe8, 0x0a, 0xb2, 0x88, 0x7d, 0x08, 0xa5,
	0x91, 0x90, 0xea, 0xb5, 0xfe, 0x73, 0xf8, 0x3e, 0x51, 0x57, 0x00, 0x7b, 0x09, 0xc5, 0xb7, 0x71,
	0x84, 0x22, 0x9a, 0xc4, 0xbc, 0x4e, 0xc5, 0x36, 0x97, 0x83, 0xa7, 0xb2, 0xd1, 0xab, 0x53, 0xb1,
	0x5d, 0x5d, 0xca, 0x8f, 0xcf, 0x3e, 0xed, 0xfd, 0x6c, 0x9f, 0x76, 0x7e, 0x6a, 0x9f, 0xd3, 0x38,
	0x28, 0x6e, 0x7e, 0xd9, 0x70, 0x57, 0xa9, 0xfa, 0xf0, 0x20, 0x1e, 0x7b, 0x01, 0xf2, 0x8f, 0xcd,
	0xe1, 0x26, 0x62, 0xfb, 0x70, 0x67, 0xf6, 0x3a, 0x8e, 0x70, 0x18, 0xa5, 0xe1, 0x08, 0x25, 0xb7,
	0x89, 0x2d, 0x13, 0x76, 0x4c, 0x10, 0xeb, 0xc1, 0xa3, 0x75, 0xc9, 0x55, 0x97, 0x4d, 0xea, 0xf2,
	0xbd, 0x35, 0xed, 0xaa, 0xd7, 0x43, 0xd8, 0xf1, 0x7c, 0x5f, 0x62, 0x92, 0xf0, 0x56, 0xcd, 0xb2,
	0xcb, 0xbd, 0xc7, 0xff, 0xf2, 0x53, 0x1b, 0x81, 0x9b, 0x2b, 0xd9, 0x11, 0x40, 0x3a, 0xd3, 0x4d,
	0xfb, 0x43, 0x4f, 0xf1, 0x09, 0xe5, 0x55, 0x1d, 0xb3, 0x7e, 0x9c, 0x7c, 0xfd, 0x38, 0xdf, 0xe5,
	0xeb, 0x87, 0xe6, 0xfa, 0x87, 0xb5, 0x51, 0xb4, 0xdc, 0x52, 0x96, 0xd7, 0x57, 0xec, 0x03, 0x28,
	0xae, 0x9e, 0xda, 0x5f, 0x16, 0x75, 0xb3, 0x02, 0xaa, 0xdf, 0xc2, 0xfd, 0x6b, 0xab, 0x84, 0x3d,
	0x80, 0xc2, 0x1b, 0x5c, 0x70, 0xa3, 0xd4, 0x9f, 0xac, 0x05, 0x5b, 0x73, 0x2f, 0x48, 0x91, 0x6f,
	0x50, 0x05, 0x0f, 0x6f, 0x54, 0xd0, 0x8f, 0x16, 0xae, 0x91, 0x3c, 0xdf, 0xf8, 0xdc, 0xaa, 0xfe,
	0x69, 0xc1, 0x4e, 0xd6, 0x8b, 0x9e, 0xe5, 0x24, 0x96, 0xa1, 0xa7, 0x14, 0xfa, 0x99, 0xe7, 0x15,
	0xa0, 0x1f, 0x4a, 0xa2, 0x24, 0xa2, 0x1a, 0xe6, 0x97, 0xb3, 0x41, 0x92, 0xbb, 0x06, 0xcd, 0x4d,
	0xaa, 0x50, 0xa4, 0xe9, 0x08, 0xb5, 0xe0, 0x05, 0xd3, 0x41, 0x1e, 0xeb, 0x39, 0x4a, 0x9c, 0x8a,
	0x38, 0xe2, 0x9b, 0x66, 0x8e, 0x26, 0x62, 0x7b, 0x50, 0x9e, 0xc5, 0x89, 0xf2, 0x82, 0xe1, 0x38,
	0xf6, 0x91, 0x6f, 0x11, 0x09, 0x06, 0x3a, 0x8a, 0x7d, 0xd4, 0x3b, 0x78, 0x1c, 0xa7, 0xba, 0x65,
	0xbe, 0x4d, 0x64, 0x1e, 0xd6, 0x5f, 0x41, 0xe5, 0x48, 0xa2, 0xa7, 0x50, 0x4f, 0xc5, 0xc5, 0x1f,
	0x52, 0x4c, 0x14, 0x7b, 0x02, 0x9b, 0xfa, 0xd6, 0xa8, 0x87, 0x72, 0xaf, 0x72, 0x63, 0x7a, 0x2e,
	0xd1, 0xba, 0xd4, 0x99, 0x97, 0x24, 0x97, 0xb1, 0xf4, 0xb3, 0x5e, 0x56, 0x71, 0xfd, 0x29, 0xb0,
	0x75, 0xdf, 0x64, 0x16, 0x47, 0x09, 0xea, 0xfb, 0x46, 0x29, 0xcd, 0xba, 0x76, 0xf5, 0x67, 0xfd,
	0x39, 0x54, 0x4e, 0x68, 0x7c, 0xef, 0x7e, 0xbe, 0x3e, 0x63, 0x3d, 0xf7, 0xbf, 0xce, 0x18, 0x6d,
	0xd3, 0xf0, 0x0e, 0xff, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xad, 0xce, 0xc4, 0x39, 0x0d, 0x07, 0x00,
	0x00,
}
