#!/usr/bin/env bash

docker run --rm -it -v `pwd`:/opt/include/n13t -w /opt/include/n13t namely/protoc-all $@


# Deprecated
# docker run --rm -it -v `pwd`:/opt/include/n13t  --entrypoint /defs/scripts/entrypoint.sh namely/protoc-all $@