// Code generated by protoc-gen-go. DO NOT EDIT.
// source: n13t/gitlab/v4/repository.proto

package n13t_gitlab_v4

import (
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Repository struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Homepage             string   `protobuf:"bytes,4,opt,name=homepage,proto3" json:"homepage,omitempty"`
	GitHttpUrl           string   `protobuf:"bytes,5,opt,name=git_http_url,json=gitHttpUrl,proto3" json:"git_http_url,omitempty"`
	GitSshUrl            string   `protobuf:"bytes,6,opt,name=git_ssh_url,json=gitSshUrl,proto3" json:"git_ssh_url,omitempty"`
	VisibilityLevel      uint32   `protobuf:"varint,7,opt,name=visibility_level,json=visibilityLevel,proto3" json:"visibility_level,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Repository) Reset()         { *m = Repository{} }
func (m *Repository) String() string { return proto.CompactTextString(m) }
func (*Repository) ProtoMessage()    {}
func (*Repository) Descriptor() ([]byte, []int) {
	return fileDescriptor_92cfb4c52aa69aab, []int{0}
}

func (m *Repository) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Repository.Unmarshal(m, b)
}
func (m *Repository) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Repository.Marshal(b, m, deterministic)
}
func (m *Repository) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Repository.Merge(m, src)
}
func (m *Repository) XXX_Size() int {
	return xxx_messageInfo_Repository.Size(m)
}
func (m *Repository) XXX_DiscardUnknown() {
	xxx_messageInfo_Repository.DiscardUnknown(m)
}

var xxx_messageInfo_Repository proto.InternalMessageInfo

func (m *Repository) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Repository) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Repository) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Repository) GetHomepage() string {
	if m != nil {
		return m.Homepage
	}
	return ""
}

func (m *Repository) GetGitHttpUrl() string {
	if m != nil {
		return m.GitHttpUrl
	}
	return ""
}

func (m *Repository) GetGitSshUrl() string {
	if m != nil {
		return m.GitSshUrl
	}
	return ""
}

func (m *Repository) GetVisibilityLevel() uint32 {
	if m != nil {
		return m.VisibilityLevel
	}
	return 0
}

func init() {
	proto.RegisterType((*Repository)(nil), "n13t.gitlab.v4.Repository")
}

func init() {
	proto.RegisterFile("n13t/gitlab/v4/repository.proto", fileDescriptor_92cfb4c52aa69aab)
}

var fileDescriptor_92cfb4c52aa69aab = []byte{
	// 233 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0xcd, 0x4a, 0x03, 0x31,
	0x14, 0x46, 0x19, 0x5b, 0xab, 0xbd, 0xf5, 0xa7, 0x64, 0x63, 0xe8, 0x42, 0x07, 0x57, 0x75, 0x33,
	0x83, 0xb4, 0x0f, 0xe1, 0xc2, 0xd5, 0x88, 0xeb, 0x21, 0x63, 0x43, 0x72, 0x21, 0x9d, 0x84, 0xe4,
	0x1a, 0xe8, 0xc3, 0xfa, 0x2e, 0x92, 0x5b, 0xac, 0xdd, 0x7d, 0x39, 0xe7, 0x24, 0x10, 0x78, 0x1a,
	0x5f, 0x37, 0xd4, 0x1a, 0x24, 0xa7, 0x86, 0x36, 0x6f, 0xdb, 0xa8, 0x83, 0x4f, 0x48, 0x3e, 0x1e,
	0x9a, 0x10, 0x3d, 0x79, 0x71, 0x57, 0x82, 0xe6, 0x18, 0x34, 0x79, 0xbb, 0x7a, 0xc8, 0xca, 0xe1,
	0x4e, 0x91, 0x6e, 0xff, 0xc6, 0x31, 0x7c, 0xfe, 0xa9, 0x00, 0xba, 0xd3, 0x6d, 0x21, 0x60, 0x3a,
	0xaa, 0xbd, 0x96, 0x55, 0x5d, 0xad, 0xe7, 0x1d, 0x6f, 0xb1, 0x84, 0xc9, 0x77, 0x74, 0xf2, 0x82,
	0x51, 0x99, 0xa2, 0x86, 0xc5, 0x4e, 0xa7, 0xaf, 0x88, 0x81, 0xd0, 0x8f, 0x72, 0xc2, 0xe6, 0x1c,
	0x89, 0x15, 0x5c, 0x5b, 0xbf, 0xd7, 0x41, 0x19, 0x2d, 0xa7, 0xac, 0x4f, 0x67, 0x51, 0xc3, 0x8d,
	0x41, 0xea, 0x2d, 0x51, 0xe8, 0xcb, 0xc3, 0x97, 0xec, 0xc1, 0x20, 0xbd, 0x11, 0x85, 0xcf, 0xe8,
	0xc4, 0x23, 0x2c, 0x4a, 0x91, 0x92, 0xe5, 0x60, 0xc6, 0xc1, 0xdc, 0x20, 0x7d, 0x24, 0x5b, 0xfc,
	0x0b, 0x2c, 0x33, 0x26, 0x1c, 0xd0, 0x21, 0x1d, 0x7a, 0xa7, 0xb3, 0x76, 0xf2, 0xaa, 0xae, 0xd6,
	0xb7, 0xdd, 0xfd, 0x3f, 0x7f, 0x2f, 0x78, 0x98, 0xf1, 0x37, 0x37, 0xbf, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x50, 0x7d, 0xea, 0xa9, 0x32, 0x01, 0x00, 0x00,
}
